name: Check lesson and build for all configs

on:
  pull_request:
  push:
    branches:
      - gh-pages

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install codespell
      run: |
        pip3 install codespell
    - name: Check spelling
      run: |
        codespell --skip="assets,*.svg,bin" --quiet-level=2  -L "rouge,dropse,namd,hist"

  check_lesson_and_build_default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install basic requirements
      run: |
        # Need this library for nokogiri
        sudo apt-get install libxslt1-dev    
        gem install bundler json kramdown kramdown-parser-gfm
        bundle config set path '.vendor/bundle'
        bundle config build.nokogiri --use-system-libraries
        bundle install
    - name: "Lint episode markdown"
      run: |
        find _episodes -name \*.md -exec bundle exec mdl -r MD001,MD003,MD005,MD006,MD007,MD008,MD009,MD010,MD011,MD012,MD015,MD016,MD017,MD018,MD019,MD020,MD021,MD022,MD023,MD025,MD035,MD036,MD037,MD038,MD039,MD046 {} \;
    - name: "Check lesson for warnings"
      run: |
        make lesson-check-all
    - name: "Check lesson for errors"
      run: |
        make lesson-check
    - name: "Check build"
      run: |
        make --always-make site

  build-specific-sites:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HPC_JEKYLL_CONFIG:
          - ComputeCanada_Graham_slurm
          - EPCC_Cirrus_pbs
          - NIST_CTCMS_slurm
          - Norway_SIGMA2_SAGA_slurm
          - UCL_Myriad_sge
          - Magic_Castle_EESSI_slurm
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install basic requirements
      run: |
        # Need this library for nokogiri
        sudo apt-get install libxslt1-dev    
        gem install bundler
        bundle config set path '.vendor/bundle'
        bundle config build.nokogiri --use-system-libraries
        bundle install
    - name: Check build ${{matrix.HPC_JEKYLL_CONFIG}}
      run: |
        make --always-make site HPC_JEKYLL_CONFIG=_includes/snippets_library/${{matrix.HPC_JEKYLL_CONFIG}}/_config_options.yml
    - name: "Lint snippet markdown"
      run: |
        find _includes/snippets_library/${{matrix.HPC_JEKYLL_CONFIG}} -name \*.snip -exec bundle exec mdl -r MD001,MD003,MD005,MD006,MD007,MD008,MD009,MD010,MD011,MD012,MD015,MD016,MD017,MD018,MD019,MD020,MD021,MD022,MD023,MD025,MD035,MD036,MD037,MD038,MD039,MD046 {} \;
